PREFIX b:<http://www.geonames.org/ontology#>
PREFIX dct:<http://purl.org/dc/terms/>
SELECT ?country (COUNT(?state) AS ?stateCount) WHERE {
    ?country a b:Country .
    ?country dct:hasPart ?state
} GROUP BY ?country